/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sist;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author EsGis02
 */
public class VentanaBusqueda extends javax.swing.JFrame {
    private String jTextcolonia= "Ingresa la colonia:";
    private String jTextagencia= "Ingresa la agencia:";
    private String jTextseccion= "Ingresa la sección:";
    private String jTextnombre= "Ingresa el nombre:";
    private String jTextapellido= "Ingresa el apellido:";
    private final int col  = 0;
    private final int agen = 1;
    private final int sec  = 2;
    private final int nomb = 3;
    private final int ape  = 4;
    private final int todo = 5;
    private int op=0;
    public DefaultTableModel modelo;
    Connection con = null;
    Statement stat = null;
    private String sqlcode=" WHERE Colonia =";
    private String configuracion[];
    /**
     * Creates new form VentanaBusqueda
     */
    public VentanaBusqueda( String Conf[]) {
        configuracion = Conf;
        initComponents();
        setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        BtnAceptar.setEnabled(false);
        //jTable1 = new JTable(modelo);
       
    }

    private VentanaBusqueda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAceptar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextBusqueda = new javax.swing.JTextField();
        jLabelParam = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnAceptar.setText("Editar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colonia", "Agencia", "Sección", "Nombre", "Apellido", "Todos" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona una opción:");

        jTextBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBusquedaActionPerformed(evt);
            }
        });

        jLabelParam.setText("Parámetro:");

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelParam)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscar)
                                .addContainerGap(200, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelParam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jTextBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(BtnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        asignaSql();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    
    public void asignaSql(){
        op = jComboBox1.getSelectedIndex();
        jTextBusqueda.setEnabled(true);
        switch (op) {
            case col : jLabelParam.setText(jTextcolonia);sqlcode=" WHERE Colonia LIKE";  break;
            case agen: jLabelParam.setText(jTextagencia);sqlcode=" WHERE Agencia LIKE";break;
            case sec : jLabelParam.setText(jTextseccion);sqlcode=" WHERE Seccion LIKE";break;
            case nomb: jLabelParam.setText(jTextnombre);sqlcode=" WHERE Nombre LIKE";break;
            case ape : jLabelParam.setText(jTextapellido);sqlcode=" WHERE Apellido LIKE";break;
            case todo: jTextBusqueda.setEnabled(false); jLabelParam.setText("Se muestran todos");sqlcode="";break;
            default: jLabelParam.setText("Parámetro:");sqlcode="";break;
        }
    }
    
    
    public void busqueda(){
        if(op < 5 && jTextBusqueda.getText().equalsIgnoreCase("") ){
            JOptionPane.showMessageDialog(null, "Ingresa una opcion en la busqueda.", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }else {
            if(op < 5) {
                sqlcode+="'%"+ jTextBusqueda.getText()+"%'";
            }
        }
        System.out.println("Buscando y llenando tabla");
        try{    
            Class.forName(configuracion[0]);
            con = DriverManager.getConnection(configuracion[1],configuracion[2],configuracion[3]); // OJO esta linea depende de tu base de datos, el 1234 es la contrasenia
            stat = con.createStatement();
            System.out.println("preparando statement :"+sqlcode);
            ResultSet rs = stat.executeQuery("select * from aspiranteresponsable"+sqlcode);
            System.out.println("Datos obtenidos configurando tabla");
            //conversorTable.rellena(rs, modelo);
            String [] titulos = {"id","Nombre", "Apellido", "Calle", "Numero", "Colonia", "Agencia", "Seccion"}; 
            String [] registros = new String[8];
            
            modelo = new DefaultTableModel(null, titulos);
            while(rs.next())
                {
                    registros[0]= rs.getString("idaspirante");
                    registros[1]= rs.getString("Nombre");
                    registros[2]= rs.getString("Apellido");
                    registros[3]= rs.getString("Calle");
                    registros[4]= rs.getString("Numero");
                    registros[5]= rs.getString("Colonia");
                    registros[6]= rs.getString("Agencia");
                    registros[7]= rs.getString("Seccion");
                    modelo.addRow(registros);
                }
            jTable1.setModel(modelo);
            rs.close();
            asignaSql();
                }catch ( ClassNotFoundException | SQLException e ){
            System.out.println("Error: " + e.getMessage());
           
        } finally {
            
            jTable1.getSelectionModel().addListSelectionListener( new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                   if (!e.getValueIsAdjusting())
                        {
                                boolean rowsAreSelected = jTable1.getSelectedRowCount() > 0;
                                 BtnAceptar.setEnabled(rowsAreSelected);
                        }
                    
                }
            } );
            jTable1.setDefaultEditor(Object.class, null);
            
        }
    }
    
 
    
    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        
        
        try {
            int a = jTable1.getSelectedRow();
            JFrame menu = new NuevoUsuario( configuracion ,Integer.parseInt(jTable1.getValueAt(a , 0).toString() ) );
            menu.setVisible(true);
            this.dispose();
            //Boton Acepta  
        } catch (SQLException ex) {
            Logger.getLogger(VentanaBusqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        busqueda();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        JFrame menu;
        try {
            menu = new NuevoUsuario(configuracion);
             menu.setVisible(true);
        this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaBusqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void jTextBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelParam;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBusqueda;
    // End of variables declaration//GEN-END:variables
}
